# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#############
#   Notes   #
#############

# This config assumes you have a Nerd Font installed and enabled in your terminal.
# I use 'FiraCode Nerd Font Mono', but you should be able to use any Nerd Font you like.

################
#   Settings   #
################

# Inserts a blank line between shell prompts
add_newline = true

# Maximum time it may take to produce the prompt
command_timeout = 3000

########################
#   Webber's colours   #
########################

# Bright pink: (bg:#D1005B fg:#23000F)
# Middle pink, bright text: (bg:#68032F fg:#F7BCD6)
# Middle pink, faded text: (bg:#68032F fg:#D7748C)
# Dark pink, regular text: (bg:#43001D fg:#C37093)
# Dark pink, highlighted: (bg:#43001D fg:#D1005B)

###############
#   Prompts   #
###############

# Right prompt. This is displayed on the right side of the terminal.
# Colours (i.e. bg and fg) are always listed from left to right.
#
# Note: Not supported in Powershell
# @see: https://starship.rs/advanced-config/#enable-right-prompt
right_format = """
[î‚¶](bg:transparent fg:#68032f)\
$time\
/\
$memory_usage\
[î‚´](fg:#68032f bg:transparent)\
"""

# Left prompt. This is displayed on the left side of the terminal.
# Colours (i.e. bg and fg) are always listed from left to right.
format = """
[î‚¶](bg:#transparent fg:#d1005b)\
$username\
[](bg:#6A1B9A fg:#[0-9A-Fa-f]*)\
$custom.dotfiles_version\
[](bg:#[0-9A-Fa-f]* fg:#6A1B9A)\
$os\
[î‚´](fg:#d1005b bg:#68032F)\
$directory\
${custom.pregit}\
$git_branch\
$git_state\
$git_metrics\
$git_status\
${custom.postgit}\
${custom.nogit}\
$package\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
$character\
"""

########################
#   Special sections   #
########################

# Exit code indicator
[character] # The name of the module we are configuring is 'character'
success_symbol = '[î‚¶](bg:#68032F fg:#D1005B)[ó±‡«](bg:#D1005B fg:#23000F)[î‚´](fg:#D1005B bg:transparent)'
error_symbol = '[î‚¶](bg:#68032F fg:#FF003E)[ó±‡«](bg:#FF003E fg:#300000)[î‚´](fg:#FF003E bg:transparent)'
format = '$symbol '

# cross-platform way to check if we are in a git repo, takes 200ms
[custom.nogit]
when = ''' git rev-parse --git-dir ; test $? = False '''
format = '[ ](bg:#68032F)'
disabled = true

# Either `Administrator`, `root` or the current user's username.
[username]
show_always = true
style_user = "bg:#d1005b fg:#23000F"
style_root = "bg:#d1005b fg:#23000F"
format = '[ $user]($style)'
disabled = false

# Displays a symbol that represents the current operating system
[os]
style = "bg:#ff005d fg:black"
format = '[ $symbol]($style)'
disabled = true # This doesn't work in pwsh in Webstorm terminal.

# The current directory
[directory]
style = "bg:#68032F fg:#F7BCD6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[hostname]
ssh_symbol = "î¬"

[memory_usage]
symbol = "ó°›"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#68032f"
format = '[$time]($style)'

#######################
#   Version control   #
#######################


[git_branch]
symbol = "ï˜"
style = "bg:#43001D fg:#C37093" # fg:#d1005b
format = '[î‚´](fg:#68032F bg:#43001D)[ $symbol](bg:#43001D fg:#D1005B)[ $branch ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bg:#43001D fg:bold red)'
rebase = '[î©¤ REBASING](bg:#43001D fg:bold green)'
merge = '[îœ§ MERGING](bg:#43001D fg:bold yellow)'
bisect = '[ğŸ” BISECTING](bg:#43001D fg:bold blue)'
am = '[AM](bg:#43001D fg:bold green)'
am_or_rebase = '[AM/REBASE](bg:#43001D fg:bold green)'
revert = '[ó°• REVERTING](bg:#43001D fg:bold red)'

[git_metrics]
added_style = "bg:#43001D fg:#00FF00"
deleted_style = "bg:#43001D fg:#FF0000"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[git_status]
style = "bg:#43001D fg:#8080ff"
conflicted = '=' # This branch has merge conflicts.
ahead = 'îª '
behind = 'îª'
diverged = 'ó±¡·'
up_to_date = ''
untracked = '?'
stashed = 'ï…•'
modified = 'ï‘„'
staged = 'î«´'
renamed = 'Â»'
deleted = 'âœ˜'
format = '([($all_status )($ahead_behind )]($style))[î‚¶](bg:#43001D fg:#68032F)'

[fossil_branch]
symbol = "ï˜"

[hg_branch]
symbol = "ï˜"

[pijul_channel]
symbol = "ï˜"

############################
#   Contexts (canonical)   #
############################

[nodejs]
symbol = "îœ˜"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ (context) ]($style)'

[package]
format = 'is [$symbol$version]($style) '
symbol = 'ğŸ“¦ '
version_format = 'v${raw}'
style = 'bold 208'
display_private = false
disabled = false

################
#   Contexts   #
################

[aws]
symbol = "îŒ½"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[c]
symbol = "î˜"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[conda]
symbol = "ï„Œ"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[dart]
symbol = "î˜"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[elixir]
symbol = "î˜­"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[elm]
symbol = "î˜¬"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[golang]
symbol = "î˜§"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[gradle]
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[haskell]
symbol = "î·"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[haxe]
symbol = "î™¦"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[java]
symbol = "î‰–"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[julia]
symbol = "î˜¤"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[lua]
symbol = "î˜ "
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[ocaml]
symbol = "î™º"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[perl]
symbol = "î™¾"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[python]
symbol = "îˆµ"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[rlang]
symbol = "ó°Ÿ”"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[ruby]
symbol = "î‘"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[scala]
symbol = "îœ·"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[swift]
symbol = "î•"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

[zig]
symbol = "îš©"
style = "bg:#68032F fg:#D7748C"
format = '[$symbol](bg:#68032F fg:#F7BCD6)[ ($version) ]($style)'

#############
#   Other   #
#############

[nix_shell]
symbol = "ïŒ“"

[os.symbols]
Alpaquita = "îª¢"
Alpine = "ïŒ€"
AlmaLinux = "ïŒ"
Amazon = "ï‰°"
Android = "ï…»"
Arch = "ïŒƒ"
Artix = "ïŒŸ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "îŠ"
Emscripten = "ïˆ…"
EndeavourOS = "ï†—"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ó°›“"
Gentoo = "ïŒ"
HardenedBSD = "ó°Œ"
Illumos = "ó°ˆ¸"
Kali = "ïŒ§"
Linux = "ïŒš"
Mabox = "î¬©"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï‡"
MidnightBSD = "ï††"
Mint = "ïŒ"
NetBSD = "ï€¤"
NixOS = "ïŒ“"
OpenBSD = "ó°ˆº"
openSUSE = "ïŒ”"
OracleLinux = "ó°Œ·"
Pop = "ïŒª"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
RockyLinux = "ïŒ«"
Redox = "ó°€˜"
Solus = "ó° ³"
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ïˆ­"
Void = "ïŒ®"
Windows = "ó°²"
